#!/usr/bin/env bash
# Installing nginx onto server.
sudo apt-get update
sudo apt-get install -y nginx

cat <<EOF | sudo tee /var/www/html/index.html > /dev/null
<!DOCTYPE html>
<html>
<head>
  <title>Hello World!</title>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
EOF

cat <<EOF | tee /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
             root /var/www/html;
             index index.html;
    }
}
EOF

sudo service nginx restart
