#!/usr/bin/env bash
# Setting up Nginx

sudo apt update -y
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/index.html

cat <<EOF | tee /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    root /etc/nginx/html;
    index index.html;

    location /redirect_me {
      return 301 http://youtube.com;
    }
}
EOF

sudo service nginx restart
