#!/usr/bin/env bash
#Install a proxy on the load balancer
apt-get update
apt-get install -y haproxy
cat << EOF >> /etc/haproxy/haproxy.cfg
frontend http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web-01 34.207.63.26:80 check
        server web-02 100.26.11.171:80 check
EOF
service haproxy restart
