#!/usr/bin/env bash
# This script checks whether the terminal input ip address belongs to a host on the network.
if [ "$1" ]; then
	ping -c5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
