#!/usr/bin/env bash
# This script displays "Best School" in a 10 step while loop and bad luck for the 4th and good luck for the 8th.
i=0
while [ "$i" -ne 10 ];
do
	((i++))
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
