#!/usr/bin/env bash
# Prints 1-20 and for Italy, China, and Japan, shows their bad luck numbers after them.
i=0
while [ "$i" -ne 20 ];
do
	((i++))
	echo "Best School"
	case $i in
		4) echo "bad luck from China"
			;;
		9) echo "bad luck from Japan"
			;;
		17) echo "bad luck from Italy"
			;;
	esac
done
