#!/usr/bin/env bash
# This displays clock time as it changes: The hour and minutes.
hour=0
minute=0
while [ 1 ];
do
	echo "Hour: $hour"
	if [ "$hour" == 12 ]; then
		break
	fi
	minute=1
	while [ "$minute" -ne 60 ];
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
