#!/usr/bin/env bash
# This displays clock time as it changes: The hour and minutes.
hour=0
minute=0
while [ "$hour" -ne 13 ];
do
	echo "Hour: $hour"
	minute=1
	while [ "$minute" -ne 60 ];
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
