#!/usr/bin/env bash
# Stop the firewall
ufw disable
# Block all incoming traffic but allow all outgoing traffic
ufw default deny incoming
ufw default allow outgoing
# Allow SSH, HTTP, and HTTPS
ufw allow ssh
ufw allow http
ufw allow https
# Enable the firewall
ufw enable
