#!/usr/bin/env bash
# Creating 4096 bit rsa-key-pair named school and protected by passphrase betty
type_="rsa"
bits="4096"
file_name="./school"
passphrase="betty"
ssh-keygen -t "$type_" -b "$bits" -f "$file_name" -N "$passphrase"
